import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/header/Header";
import Footer from "@/components/Footer";

const simplonNorm = localFont({
  src: "./fonts/SimplonNorm-Regular-WebS.woff",
  variable: "--font-simplon-norm",
  weight: "100 400",
});

const simplonNormBold = localFont({
  src: "./fonts/SimplonNorm-Bold-WebS.woff",
  variable: "--font-simplon-norm-bold",
  weight: "400 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${simplonNorm.variable} ${simplonNormBold.variable}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
