import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const simplonNorm = localFont({
  src: "./fonts/SimplonNorm-Regular-WebS.woff",
  variable: "--font-simplon-norm",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${simplonNorm.variable}`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
